name: pt1.7.1
channels:
- simpleitk
- pytorch
- anaconda
- conda-forge
- defaults
dependencies:
- autopep8=1.5.7
- ipykernel=5.5.5
- ipython=7.16.1
- matplotlib=3.3.2
- nltk=3.5
- parallel=20210822
- pylint=2.7.4
- scikit-image=0.17.2
- screen=4.8.0
- simpleitk=2.0.2
- yapf=0.31.0
- pip:
  - argon2-cffi==21.1.0
  - async-generator==1.10
  - attrs==21.2.0
  - beautifulsoup4==4.10.0
  - bleach==4.1.0
  - cffi==1.15.0
  - chardet==3.0.4
  - click==8.0.3
  - colorama==0.4.4
  - configargparse==1.5.3
  - configparser==5.0.2
  - cryptography==35.0.0
  - defusedxml==0.7.1
  - docker-pycreds==0.4.0
  - docopt==0.6.2
  - docutils==0.17.1
  - einops==0.4.0
  - filelock==3.4.1
  - gdown==4.4.0
  - gitdb==4.0.7
  - gitpython==3.1.18
  - gputil==1.4.0
  - grad-cam==1.3.7
  - idna==2.10
  - importlib-metadata==4.8.1
  - install==1.3.5
  - ipywidgets==7.6.5
  - jeepney==0.7.1
  - jinja2==3.0.3
  - joblib==1.1.0
  - jsonschema==3.2.0
  - jupyter==1.0.0
  - jupyter-console==6.4.0
  - jupyterlab-pygments==0.1.2
  - jupyterlab-widgets==1.0.2
  - keyring==23.2.1
  - littleutils==0.2.2
  - lmdb==1.2.1
  - markupsafe==2.0.1
  - mistune==0.8.4
  - nbclient==0.5.9
  - nbconvert==6.0.7
  - nbformat==5.1.3
  - notebook==6.4.6
  - ogb==1.3.2
  - onnx==1.10.2
  - opencv-python==4.5.5.62
  - outdated==0.2.1
  - packaging==21.0
  - pandas==1.1.5
  - pandocfilters==1.5.0
  - pathtools==0.1.2
  - pipreqs==0.4.10
  - pkginfo==1.7.1
  - prometheus-client==0.12.0
  - promise==2.3
  - protobuf==3.18.1
  - psutil==5.8.0
  - pthflops==0.4.1
  - pycparser==2.20
  - pyrsistent==0.18.0
  - pysocks==1.7.1
  - pytorch-ignite==0.5.0.dev20220202
  - pytz==2020.4
  - pyyaml==5.3.1
  - qtconsole==5.2.1
  - qtpy==1.11.3
  - readme-renderer==30.0
  - requests==2.25.0
  - requests-toolbelt==0.9.1
  - rfc3986==1.5.0
  - scikit-learn==0.24.2
  - scipy==1.5.4
  - secretstorage==3.3.1
  - send2trash==1.8.0
  - sentry-sdk==1.4.3
  - shortuuid==1.0.1
  - simdkalman==1.0.2
  - smilelogging==0.2.5
  - smmap==4.0.0
  - soupsieve==2.3.1
  - subprocess32==3.5.4
  - termcolor==1.1.0
  - terminado==0.12.1
  - testpath==0.5.0
  - thop==0.0.5-2201250148
  - threadpoolctl==3.0.0
  - timm==0.6.1
  - torch==1.10.2
  - torchstat==0.0.7
  - tqdm==4.62.3
  - ttach==0.0.3
  - twine==3.4.2
  - urllib3==1.26.2
  - wandb==0.12.9
  - webencodings==0.5.1
  - widgetsnbextension==3.5.2
  - wilds==2.0.0
  - yarg==0.1.9
  - yaspin==2.1.0
  - zipp==3.6.0
